【問題1】アイテムベース
以下のような架空の旅行者のデータを使って簡単なアイテムベースのレコメンドを行う。 
下の表は、ハワイ、グアム、ロンドン、ニューヨークへ訪れた回数を記録した6人分の旅行者のデータである。   
  
アイテム間の類似度行列を作る 
例えば、「ハワイ」と「ハワイとそのほかの国」とのコサイン類似度を計算してみると以下のように計算できる。 
これを各国分、計算して、類似度行列を出してみよう。  

ユーザのベクトルと類似度行列の積を取り推薦する 
類似度行列との対象ユーザのベクトルとの内積をとってみよう。
ここで出た値が一番高いものが次に旅行者が旅先に選ぶ可能性の高い国です。 
この国を出力してください。  

In [2]:
import pandas as pd
import numpy as np

In [7]:
data = pd.DataFrame([[1,2,4,3], [1,1,2,4], [3,5,2,2], [3,4,2,3], [3,3,0,4], [3,3,1,4]], columns=['Hawaii', 'Guam', 'London', 'NewYork'])

In [9]:
def cosine_similarity_matrix (vectors):
    unit_vectors = vectors / np.linalg.norm(vectors, axis=1, keepdims=True)
    return np.matmul(unit_vectors, unit_vectors.T)

In [14]:
cos_similarity_matrix = cosine_similarity_matrix(data.values.T)

In [20]:
print("Cos類似度")
print('Hawaii    Guam    London    NewYork')
cos_similarity_matrix

Cos類似度
Hawaii    Guam    London    NewYork


array([[1.        , 0.97332853, 0.63259899, 0.89190174],
       [0.97332853, 1.        , 0.71956944, 0.83666003],
       [0.63259899, 0.71956944, 1.        , 0.75462449],
       [0.89190174, 0.83666003, 0.75462449, 1.        ]])

In [28]:
user_vector = [1,0,0,0]

In [29]:
dot = np.dot(user_vector, cos_similarity_matrix)

In [30]:
print('Hawaii    Guam    London    NewYork')
dot

Hawaii    Guam    London    NewYork


array([1.        , 0.97332853, 0.63259899, 0.89190174])

結果, Hawaiiが一番数値が大きかったが、これまで一度も行ったことがない国という条件をつけるとGuamがオススメである。

【アドバンス課題1】 アイテムベースの改善
課題１では対象ユーザの訪問国は、一つだけでしたが２カ国訪問していても対応できるようにしてください。

In [31]:
user_vector = [1,2,5,3]

In [32]:
dot = np.dot(user_vector, cos_similarity_matrix)

In [33]:
print('Hawaii    Guam    London    NewYork')
dot

Hawaii    Guam    London    NewYork


array([8.78535726, 9.08115578, 9.33561135, 9.33834427])

NewYorkがオススメである。

【問題2】ユーザーベース
以下のようなデータがあった時に、user１に対して、レコメンドする方法を考えていきます。　　

ユーザーベースの手法は同じようなユーザを見つけてそのユーザと同じようなレコメンドをします。 
今回の方法は厳密なレコメンド手法とは異なりますが、実装を通して大まかなイメージを掴みましょう。  
方法  
ユーザーごとの相関行列を出す。   
ユーザーごとの相関行列を出してください。(今回はピアソンを使いましょう。)  
アイテムベースの時は、アイテムに対して類似度行列を出しましたが、今回はユーザに対して使います。  
評価の高い方を推薦する   
相関を出したら、最も相関の高い人のレコメンド結果を使ってuser1に対してレコメンドしてください。  

In [45]:
data = pd.DataFrame([[2,2,4,np.nan, np.nan], [1,1,2,4,3], [0,5,2,2,5], [2,4,2,3,4], [1,3,0,4,1]], 
                    columns=['ゼロから作るDeepLearning', 
                             'Python機械学習プログラミング', 
                             'ゼロから作るDeepLearning-自然言語処理編-', 
                             'はじめてのパターン認識',
                            'これからの強化学習'])

In [43]:
def pearson_corr(x, y):
    x_diff = x - np.mean(x)
    y_diff = y - np.mean(y)
    return np.dot(x_diff, y_diff) / (np.sqrt(sum(x_diff ** 2)) * np.sqrt(sum(y_diff ** 2)))

In [48]:
#nanを平均値で埋める
data = pd.DataFrame([[2,2,4,3, 3], [1,1,2,4,3], [0,5,2,2,5], [2,4,2,3,4], [1,3,0,4,1]], 
                    columns=['ゼロから作るDeepLearning', 
                             'Python機械学習プログラミング', 
                             'ゼロから作るDeepLearning-自然言語処理編-', 
                             'はじめてのパターン認識',
                            'これからの強化学習'])

In [49]:
print("user1, user2, user3, user4, user5")
np.corrcoef([data[0:1].values[0], data[1:2].values[0], data[2:3].values[0], data[3:4].values[0], data[4:5].values[0]])

user1, user2, user3, user4, user5


array([[ 1.        ,  0.50418417, -0.02756589, -0.29880715, -0.40006613],
       [ 0.50418417,  1.        ,  0.10613237,  0.19174125,  0.37340802],
       [-0.02756589,  0.10613237,  1.        ,  0.92253121,  0.19650211],
       [-0.29880715,  0.19174125,  0.92253121,  1.        ,  0.45643546],
       [-0.40006613,  0.37340802,  0.19650211,  0.45643546,  1.        ]])

In [50]:
data[1:2]

ゼロから作るDeepLearning  Python機械学習プログラミング  ゼロから作るDeepLearning-自然言語処理編-  \
1                   1                  1                            2   

   はじめてのパターン認識  これからの強化学習  
1            4          3

user1に対してuser2が一番相関どが高い。
user2の中で最もひょう