【課題1】内積を手計算しよう

$$
    A = \left[\begin{array}{c}
            -1 & 2 & 3 \\
            4 & -5 & 6 \\
            7 & 8 & -9 \\
        \end{array}\right], B = \left[\begin{array}{c}
            0 & 2 & 1\\
            0 & 2 & -8 \\
            2 & 9 & -1 \\
        \end{array}\right]
$$

$$
    A*B = \left[\begin{array}{c}
            -1\times0 + 2\times0 + 3\times2 & -1\times2 + 2\times2 + 3\times9 & -1\times1 + 2\times-8 + 3\times-1\\
            4\times0 + -5\times0 + 6\times2 & 4\times2 + -5\times2 + 6\times9 & 4\times1 + -5\times-8 + 6\times-1\\
            7\times0 + 8\times0 + -9\times2 & 7\times2 + 8\times2 + -9\times9 & 7\times1 + 8\times-8 + -9\times-1\\
          \end{array}\right]  
        = \left[\begin{array}{c}
            6 & 29 & -20 \\
            12 & 52 & 38 \\
            -18 & -51 & -48 \\
          \end{array}\right]
$$
    

In [40]:
"""
【課題2】1次元配列の内積をfor文で計算しよう
"""
import numpy as np

A_ROW = 0
B_COLUMN = 0
#内積A*Bの要素(A_ROW, B_COLUMN)を計算

MAT_A = np.matrix([[-1, 2, 3],[4, -5, 6],[7, 8, -9]])
MAT_B = np.matrix([[0, 2, 1],[0, 2, -8],[2, 9, -1]])

result = 0
for n in range(3):
    #print(mat_A[0:1,n:n+1])
    #print(mat_B[n:n+1,1:2])
    result += MAT_A[A_ROW:A_ROW+1,n:n+1] * MAT_B[n:n+1,B_COLUMN:B_COLUMN+1] 

print(result)

[[6]]


In [85]:
"""
【課題3】多次元配列の内積をfor文で計算しよう
"""
MAT_A_NUM_OF_ROW = 3
MAT_A_NUM_OF_COLUMN = 3
MAT_B_NUM_OF_COLUMN = 3

MAT_A = np.matrix([[-1, 2, 3],[4, -5, 6],[7, 8, -9]])
MAT_B = np.matrix([[0, 2, 1],[0, 2, -8],[2, 9, -1]])

mat_cal_result = np.empty((MAT_A_NUM_OF_ROW, MAT_B_NUM_OF_COLUMN))
for a_row in range(MAT_A_NUM_OF_ROW):
        for b_column in range(MAT_B_NUM_OF_COLUMN):
            cal_result=0
            for n in range(MAT_A_NUM_OF_COLUMN):
                #print( "A({},{}) B({},{})  {} x {}".format(a_row,a_column,b_column,b_row,MAT_A[a_row:a_row+1,n:n+1],MAT_B[n:n+1,b_column:b_column+1]))
                cal_result += MAT_A[a_row:a_row+1,n:n+1] * MAT_B[n:n+1,b_column:b_column+1]
            
            mat_cal_result[a_row, b_column] = cal_result
            #print("{} \n".format(cal_result))

print("内積A*B= \n {}".format(mat_cal_result))

内積A*B= 
 [[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [88]:
"""
【課題4】内積をnp.dotで計算しよう
"""

mat_cal_result_by_npdot = np.dot(MAT_A,MAT_B)
print("np.dot(A*B)= \n {}".format(mat_cal_result_by_npdot))

np.dot(A*B)= 
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


課題3と課題4の結果は一致する。

In [94]:
"""
【課題5】内積ができないときはどうするか
エラーとなる場合
"""

MAT_A = np.matrix([[-1, 2, 3],[4, -5, 6]])
MAT_B = np.matrix([[9, 8, 7],[6, 5, -4]])

mat_cal_result = np.dot(MAT_A,MAT_B)
print("np.dot(A*B)= \n {}".format(mat_cal_result))

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

【課題5】内積ができないときはどうするか
なぜエラーとなるか？

内積A*Bの各要素は、Aの行とBの列の要素を掛け合わせた値の合計として計算される。よってAの列数とBの行数が同じでなければ計算できない。
課題5の場合、行列A,Bは2行3列であるからAの列数＝３とBの行数＝２であるため計算できない。
計算を実行するために、行列Bの行と列を入れ替えて（転置）3行2列の行列を作り、行列Aと行列Bの転置の内積を計算をする。

In [95]:
"""
【課題5】内積ができないときはどうするか
行列Bを転置して計算を実行
"""

MAT_A = np.matrix([[-1, 2, 3],[4, -5, 6]])
MAT_B = np.matrix([[9, 8, 7],[6, 5, -4]])

#print(MAT_B.T)
mat_cal_result = np.dot(MAT_A,MAT_B .T)
print("np.dot(A*B)= \n {}".format(mat_cal_result))

np.dot(A*B)= 
 [[ 28  -8]
 [ 38 -25]]
