#### 【問題1】これまで利用してきたクラスの列挙
クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。
最低でもPandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

1.Pandas   
DataFrame()  
Series()  

2.matplotlib  
subplot2grid()  
figure()  

3.scikit-learn  
KNeighborsClassifier()  
LogisticRegression()  
SVC()  
DecisionTreeClassifier()  
RandomForestClassifier()  

#### 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙
これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。
最低でもそれぞれ5つ以上答えてください。

1.Method
PandasDataFrame.shape()  
PandasDataFrame.append()  
PandasDataFrame.astype()  
PandasDataFrame.combine()  
PandasDataFrame.describe()  
PandasDataFrame.info()  
PandasDataFrame.head()  

2.instance変数  
PandasDataFrame : data    
PandasDataFrame : dtype    
PandasDataFrame : index  
PandasDataFrame : column  
KNeighborsClassifier : n_neighbors  
KNeighborsClassifier : algorithm

#### 【問題3】標準化クラスをスクラッチで作成
理解をより深めるため、StandardScalerをスクラッチで作成しましょう。scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的にはfitメソッドとtransformメソッドを作ります。

In [1]:
import numpy as np

In [2]:
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """

    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            学習データ
        """

        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.var(X, axis=0)

        pass

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        
        X_scaled = (X - self.mean_) / np.sqrt(self.var_)
        
        return X_scaled

In [3]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 :", scratch_scaler.mean_)
print("分散 :", scratch_scaler.var_)
X_std = scratch_scaler.transform(X)
print("標準化X：", X_std)

#答え
scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std_ans = scaler.transform(X)
print("標準化X：", X_std_ans)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
標準化X： [[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]
平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
標準化X： [[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.069044

#### 【課題4】 四則演算を行うクラスの作成
上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。
また、コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合には警告文を出し、self.value=0とするコードを追加してください。
クラス名や説明文も適切に書き換えてください。

In [5]:
class ArithmeticClass():
    """
    四則演算を行うクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        if type(value) is int:
            self.value = value
            print("初期値{}が設定されました".format(self.value))
        else:
            self.value = 0
            print("{}は入力できません。パラメータは数値のみ入力可能です。".format(value)) 
            print("初期値{}が設定されました".format(self.value))            
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
    def sub(self, value2):
        """
        受け取った引数をself.valueから引く
        """
        self.value -= value2
    def multi(self, value2):
        """
        受け取った引数でself.valueを掛ける
        """
        self.value *= value2
    def div(self, value2):
        """
        受け取った引数でself.valueを割る
        """
        self.value /= value2 


example = ArithmeticClass(6)
print("value :", example.value)
example.add(3)
print("Add => value :", example.value)
example.sub(3)
print("Sub => value :", example.value)
example.multi(3)
print("Multi => value :", example.value)
example.div(3)
print("Div => value :", example.value)

初期値6が設定されました
value : 6
Add => value : 9
Sub => value : 6
Multi => value : 18
Div => value : 6.0
