In [2]:
import pandas as pd
import numpy as np
from sklearn.decomposition import NMF

【問題１】欠損値を埋める

In [4]:
data1 = pd.DataFrame({"ゼロから作るDeepLearning":[2,1,0,2,1],
                       "Python機械学習プログラミング":[2,1,5,4,3],
                       "ゼロから作るDeepLearning-自然言語処理編-":[4,2,2,2,0],
                       "はじめてのパターン認識":[np.nan,4,2,3,4],
                      "これからの強化学習":[np.nan, 3,5,4,1]},index=["user1","user2","user3","user4","user5"])

In [15]:
data1 = data1.fillna(0)

【問題2】非負値行列因子分解(NMF)をScikit-learnで実装

In [16]:
model = NMF(n_components=5, init='nndsvda')
W = model.fit_transform(data1.values)
H = model.components_

In [21]:
W

array([[0.00000000e+00, 0.00000000e+00, 6.20076885e-07, 2.51200316e-02,
        6.87076666e-07],
       [5.70317023e-02, 4.62932283e-01, 0.00000000e+00, 6.66305225e-03,
        0.00000000e+00],
       [6.00353143e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.49846856e-02],
       [4.32364215e-02, 1.51084101e-01, 8.74101987e-01, 1.01222026e-02,
        5.99614137e-01],
       [0.00000000e+00, 8.56424131e-03, 2.87721309e-01, 0.00000000e+00,
        1.62492841e+00]])

In [18]:
H

array([[0.00000000e+00, 8.24396113e+00, 3.33139406e+00, 3.19262807e+00,
        8.32735093e+00],
       [1.01416134e+00, 0.00000000e+00, 1.61727226e+00, 8.24713306e+00,
        5.45429214e+00],
       [8.79238080e-01, 2.25235649e+00, 0.00000000e+00, 2.16899753e-01,
        3.20921173e+00],
       [7.96169865e+01, 7.96179386e+01, 1.59235695e+02, 0.00000000e+00,
        0.00000000e+00],
       [4.54173003e-01, 1.44761184e+00, 0.00000000e+00, 2.37965743e+00,
        1.83542354e-02]])

In [22]:
WH = np.dot(W, H)
WH

array([[1.99998207e+00, 2.00000752e+00, 4.00000567e+00, 1.76950162e-06,
        2.00256878e-06],
       [9.99980167e-01, 1.00066562e+00, 1.99967837e+00, 3.99994515e+00,
        2.99989091e+00],
       [1.58890997e-02, 4.99993222e+00, 2.00001289e+00, 1.99995586e+00,
        4.99999342e+00],
       [1.99999523e+00, 3.99914609e+00, 2.00019764e+00, 3.00051724e+00,
        4.00028549e+00],
       [9.99659669e-01, 3.00031656e+00, 1.38507099e-02, 3.99981008e+00,
        9.99894793e-01]])

In [27]:
data1[0:1].values

array([[2., 2., 4., 0., 0.]])

In [39]:
WH = np.round(WH)

In [40]:
print("index=1")
print("1:{} \n {}".format(data1[0:1].values, WH[0]))
print("index=2")
print("2:{} \n {}".format(data1[1:2].values, WH[1]))
print("index=3")
print("3:{} \n {}".format(data1[2:3].values, WH[2]))
print("index=4")
print("4:{} \n {}".format(data1[3:4].values, WH[3]))
print("index=5")
print("5:{} \n {}".format(data1[4:5].values, WH[4]))

index=1
1:[[2. 2. 4. 0. 0.]] 
 [2. 2. 4. 0. 0.]
index=2
2:[[1. 1. 2. 4. 3.]] 
 [1. 1. 2. 4. 3.]
index=3
3:[[0. 5. 2. 2. 5.]] 
 [0. 5. 2. 2. 5.]
index=4
4:[[2. 4. 2. 3. 4.]] 
 [2. 4. 2. 3. 4.]
index=5
5:[[1. 3. 0. 4. 1.]] 
 [1. 3. 0. 4. 1.]


変換後の行列の内積は元の行列と等しい

【アドバンス課題1】 Scikit-learnで実装

In [3]:
# データの読み込み
ratings = pd.read_csv('./anime_data/rating.csv')
anime = pd.read_csv('./anime_data/anime.csv')
# 1000人以上評価しているもののみを取得
anime = anime[anime['members'] > 1000]
# 未評価のものは-1が入っているが、nanのものは削除
anime = anime.dropna()
ratings[ratings.rating == -1]=0
# マージ
merge_df = ratings.merge(anime, left_on = 'anime_id', right_on = 'anime_id', suffixes= ['_user', '']) 
# 重複しているものを削除
merge_df = merge_df.drop_duplicates(['user_id','name'])
anime_pivot = merge_df.pivot(index= 'user_id',columns='name',values='rating').fillna(0)
anime_pivot.head()

name     &quot;0&quot;  &quot;Bungaku Shoujo&quot; Kyou no Oyatsu: Hatsukoi  \
user_id                                                                       
1                  0.0                                                0.0     
2                  0.0                                                0.0     
3                  0.0                                                0.0     
5                  0.0                                                0.0     
7                  0.0                                                0.0     

name     &quot;Bungaku Shoujo&quot; Memoire  &quot;Bungaku Shoujo&quot; Movie  \
user_id                                                                         
1                                       0.0                               0.0   
2                                       0.0                               0.0   
3                                       0.0                               0.0   
5                                       0.0                               0.0   
7                                       0.0                               0.0   

name     .hack//G.U. Returner  .hack//G.U. Trilogy  \
user_id                                              
1                         0.0                  0.0   
2                         0.0                  0.0   
3                         0.0                  0.0   
5                         0.0                  0.0   
7                         0.0                  0.0   

name     .hack//G.U. Trilogy: Parody Mode  .hack//Gift  .hack//Intermezzo  \
user_id                                                                     
1                                     0.0          0.0                0.0   
2                                     0.0          0.0                0.0   
3                                     0.0          0.0                0.0   
5                                     0.0          0.0                0.0   
7                                     0.0          0.0                0.0   

name     .hack//Liminality        ...          gdgd Fairies  gdgd Fairies 2  \
user_id                           ...                                         
1                      0.0        ...                   0.0             0.0   
2                      0.0        ...                   0.0             0.0   
3                      0.0        ...                   0.0             0.0   
5                      0.0        ...                   0.0             0.0   
7                      0.0        ...                   0.0             0.0   

name     iDOLM@STER Xenoglossia  iDOLM@STER Xenoglossia Specials  s.CRY.ed  \
user_id                                                                      
1                           0.0                              0.0       0.0   
2                           0.0                              0.0       0.0   
3                           0.0                              0.0       0.0   
5                           0.0                              0.0       0.0   
7                           0.0                              0.0       0.0   

name     xxxHOLiC  xxxHOLiC Kei  xxxHOLiC Movie: Manatsu no Yoru no Yume  \
user_id                                                                    
1            0.00           0.0                                      0.0   
2            0.00           0.0                                      0.0   
3            0.00           0.0                                      0.0   
5            8.11           0.0                                      0.0   
7            0.00           0.0                                      0.0   

name     xxxHOLiC Rou  xxxHOLiC Shunmuki  
user_id                                   
1                 0.0                0.0  
2                 0.0                0.0  
3                 0.0                0.0  
5                 0.0                0.0  
7                 0.0                0.0  

[5 rows x 6634 columns]

In [4]:
len(anime_pivot.columns.values)

6634

In [5]:
model = NMF(n_components=3, init='nndsvd')
W = model.fit_transform(anime_pivot.values)
H = model.components_

In [6]:
mat = np.dot(W, H)

In [7]:
mat

array([[1.74602487e-04, 6.67948600e-03, 8.62070314e-03, ...,
        1.58371950e-03, 6.99357232e-03, 6.01382866e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [6.35232222e-05, 2.64971140e-03, 2.42426694e-03, ...,
        1.24604290e-02, 6.66382367e-03, 9.36828461e-03],
       [5.83157522e-03, 2.41592205e-01, 2.27927022e-01, ...,
        1.05420950e+00, 5.80666101e-01, 8.05842179e-01],
       [9.82901708e-05, 4.08706721e-03, 3.79279382e-03, ...,
        1.85842224e-02, 1.00697741e-02, 1.40751709e-02]])

【アドバンス課題2】 推薦

In [ ]:
def recomendation(user_id):
    user = mat[user_id]
    index = np.argsort(user)[::-1]
    anime_list = anime_pivot.columns[index[0:50]]
    for i, name in enumerate(anime_list):
        print("Rank:{}   Title:{}".format(i+1, name))

In [15]:
user_id = 0
recomendation(user_id)

Rank:1   Title:Shingeki no Kyojin
Rank:2   Title:Sword Art Online
Rank:3   Title:No Game No Life
Rank:4   Title:Tokyo Ghoul
Rank:5   Title:Death Note
Rank:6   Title:Mirai Nikki (TV)
Rank:7   Title:Angel Beats!
Rank:8   Title:Fullmetal Alchemist: Brotherhood
Rank:9   Title:Steins;Gate
Rank:10   Title:Noragami
Rank:11   Title:One Punch Man
Rank:12   Title:Ao no Exorcist
Rank:13   Title:Kiseijuu: Sei no Kakuritsu
Rank:14   Title:Another
Rank:15   Title:Akame ga Kill!
Rank:16   Title:Psycho-Pass
Rank:17   Title:Code Geass: Hangyaku no Lelouch
Rank:18   Title:Hataraku Maou-sama!
Rank:19   Title:Toradora!
Rank:20   Title:Death Parade
Rank:21   Title:Sword Art Online II
Rank:22   Title:Code Geass: Hangyaku no Lelouch R2
Rank:23   Title:Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.
Rank:24   Title:Fate/Zero
Rank:25   Title:Shigatsu wa Kimi no Uso
Rank:26   Title:Kill la Kill
Rank:27   Title:Boku dake ga Inai Machi
Rank:28   Title:Zankyou no Terror
Rank:29   Title:Guilty Crown
Rank:3